---
- name: Add Icinga APT key
  apt_key:
    url: https://packages.icinga.com/icinga.key

- name: Add Icinga APT repository
  apt_repository:
    repo: deb http://packages.icinga.com/{{ ansible_distribution | lower }} icinga-{{ ansible_distribution_release }} main
    filename: icinga
    update_cache: true

- name: Install required packages
  apt:
    name:
      - python-psycopg2
      - git
      - icingaweb2
      - icingaweb2-module-monitoring
      - icingaweb2-module-doc
      - php-pgsql
      - php-imagick
      - php-intl
      - php-xml
      - php-mbstring

- name: Clone modules
  git:
    repo: "{{ item.value }}"
    dest: "/usr/share/icingaweb2/modules/{{ item.key }}"
    force: true
    depth: 1
  loop: "{{ icingaweb2_modules_to_clone | combine(default_modules_to_clone) | dict2items }}"

- name: Download background image
  get_url:
    url: https://i.imgur.com/SCfMd.png
    dest: /usr/share/icingaweb2/modules/unicorn/public/img/unicorn.png
    mode: 0644
    owner: root
    group: icingaweb2

- import_tasks: database.yml
  when: icingaweb2_configure_postgres

- import_tasks: configuration.yml
